# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Final_Project_MVP' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  target 'Final_Project_MVPTests' do
        inherit! :search_paths
	pod 'OCMock'
    end
end
